version: '3'
services:
  nginx:
    build:
      context     : ./nginx
    depends_on:
      - php-fpm
    container_name: socym-laravel-nginx
    hostname      : socym-laravel-nginx
    ports:
      - 8001:80
    volumes:
      - ./opt:/opt:cached

  php-fpm:
    build:
      context     : ./php-fpm
    container_name: socym-laravel-php-fpm
    hostname      : socym-laravel-php-fpm
    volumes:
      - ./opt:/opt:cached

  mysql:
    build:
      context            : ./mysql
    container_name       : socym-laravel-mysql
    hostname             : socym-laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE     : testdb
      MYSQL_USER         : testuser
      MYSQL_PASSWORD     : password
    ports:
      - '33062:3306'
